### PR TITLE
Bring back UPS configuration form

### PR DESCRIPTION
**Pull request by jtapia**

### CODE REVIEW

**Comment by forkata** [comment]
Hey @jtapia, thanks for your contribution. 

Would you mind splitting out the linting changes from the functional ones. 

Was this accidentally removed in this change https://github.com/solidusio-contrib/solidus_active_shipping/pull/49/commits/25caefd4515e2df4f14c859e5a8df386ba21febe

**Comment by jtapia** [comment]
yes, @forkata this was accidentally removed, I made some changes https://github.com/solidusio-contrib/solidus_active_shipping/commit/b9b4e9446bcb1c7f5866fdb4e71969b5e14b9c4f, but I started removing UPS because on `v2.2` of `active_shipping` they removed the UPS support https://github.com/Shopify/active_shipping/blob/master/CHANGELOG.md, could you help me taking a look on this changes, please?

**Comment by jtapia** [comment]
@forkata done, I split the changes, this is only the accidentally removed fields

**Comment by forkata** [comment]
It looks like you are also linting the file and replacing the double quotes. We generally prefer keeping those changes separate for easy review of the history.

**Comment by jtapia** [comment]
@forkata done, I updated the PR

**Comment by forkata** [comment]
You can ignore the `mysql` failures for now. I will PR something to lock the gem version down on master and then you can rebase this change to get it to pass the specs.

**Comment by jtapia** [comment]
@forkata got it, thanks, I tried to fix the `mysql` issue using `0.4.4` version but with this, one test from `pg` gets broken https://travis-ci.org/solidusio-contrib/solidus_active_shipping/builds/357246782

**Comment by jtapia** [comment]
@forkata this is the issue https://travis-ci.org/solidusio-contrib/solidus_active_shipping/jobs/357565410

**Comment by forkata** [comment]
You can rebase this now, I just merged #56! Thanks again for your work here!

**Comment by jtapia** [comment]
@forkata done https://travis-ci.org/solidusio-contrib/solidus_active_shipping/builds/358613288?utm_source=github_status&utm_medium=notification

**Comment by jtapia** [comment]
@forkata I think we can merge this, it should be the flaky test, what do you think?

**Pull request merged**
