### PR TITLE
Add integration test for FedEx calculators

### PR DESCRIPTION
**Pull request by forkata**
This change depends on #11

This change adds integration tests for each of the FedEx calculators for
which we can get rates. There are no tests for any of the `Freight`
calculators, since this extension doesn't seem to support passing of
options to the `carrier.find_rates` method, which would be needed to get
freight rates.

I was not able to get rates for any of the `Saturday` delivery calculators
as well with the addresses I am using for testing. We would need to
investigate further how we can test those.

### CODE REVIEW

**Comment by fredericboivin** [comment]
Were the tests failures caused by dead calculators or did you fix something? (just noticed that build is now green)

**Comment by forkata** [comment]
Unfortunately it seems like FedEx is not as stable as UPS and sometimes we don't get a response back :( I retried the build and that fixed the tests. I will probably run this 100 times and see how many failures we get. We may have to VCR/mock these if they are not stable enough.

**Comment by forkata** [comment]
Added VCR and cassettes for Fedex calculators. This should pass tests consistently now.

**Comment by fredericboivin** [comment]
:shipit:

**Pull request merged**
